---
title: "Readme"
output: output: rmarkdown::github_document
---

Analysing the reliability of metrics across different MOTU clustering levels:

This code is for comparing how reliable your conclusions are in inter-network analyses using metabarcoding data. I'd strongly recommend against using it for anything too serious yet as its all currently a bit unfinished. If you want to use it I'd advise contacting me first. The paper this code is supporting isn't submitted yet, and so manuals and data will be uploaded in due course.

(Dave Hemprich-Bennett, hemprich.bennett@gmail.com, @hammerheadbat)
Extremely crude vignette:
``
library(LOTUS)
library(bipartite)
library(ggplot2)
data(batnets)

ind <- desired_mets <- c('functional complementarity',
                         'web asymmetry',
                         'Fisher alpha', 'mean number of shared partners',
                         'niche overlap',
                         'nestedness',
                         'discrepancy',
                         'ISA')
m <- metcalcs(networks= batnets, indices = ind, network_level = 'higher')

g <- ggplot(m , aes(x = clustering, y = value, color = network)) +
  geom_point()+
  labs(x = 'clustering') +
  geom_smooth(method = lm, se = T)+
  scale_x_continuous(breaks = seq(91, 98, 1))+
  facet_wrap(~ metric, scales = 'free_y')+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
g


line_plot(input = m, network = 'network', clustering = 'clustering', metric = 'metric', value = 'value', plotname = 'trial datasets')
``
